commit
Oliko136/project-16-icecream pull request #31
Opened 2021-12-05 10:27 UTC by Meriel92

сделала пока что только под мобильную версию

2021-12-05 12:01 UTC, Oliko136 requested changes

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  background: var(--secondary-text-color);
тут белый есть в переменных как --primary-bg-color, лучше тут использовать его как цвет фона из переменных, чтоб было понятней

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  font-style: normal;
font style normal можно не писать, это значение по умолчанию

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  font-family: DM Sans;
этот шрифт есть в переменных как var(--primary-font)

2021-12-05 12:01 UTC, Oliko136 commented on src/partials/contacts.html
> +          <a class="contacts__adress--tel" href="tel:+61(0)383766284">+61(0) 383 766 284 </a>
очепятка - "address"

2021-12-05 12:01 UTC, Oliko136 commented on src/partials/contacts.html
> +        <p class="contacts-text-pre__title contacts__foodtrack">FOOD TRUCK</p>
очепятка - "foodtruck"

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 768px) and (max-width: 1279px) {
768px = переменная $tablet

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 1280px) {
1280px = переменная $desktop

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  background: #f0d1a5;
background-color

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  line-height: 18px;
тут line height через множитель забыла сделать) и удалить коммент из фигмы внизу

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  margin-top: 25px;
маржин топ не нужно, так как ты уже писала маржин ботом верхнему элементу, он тогда будет в два раза больше

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +  display: flex;
в мобильной версии должно работать без флексов, так как все и так идет в колонку. Можно задать тут просто маржин 0 авто

2021-12-05 12:01 UTC, Oliko136 commented on src/sass/layout/_contacts.scss
> +    flex-wrap: wrap;
тут и в десктопной flex-wrap и flex-direction не нужен: flex-wrap потому что это используется для переноса на новую строку, а тут только одна строка; а flex-direction потому что если ты удалишь флекс в колонку в моб версии, то тут флекс будет по умолчанию в строку

2021-12-05 17:54 UTC, Meriel92 commented on src/sass/layout/_contacts.scss
> +  margin-top: 25px;
не получается без маржина топа, слишком близко получается текст к тексту, а с топом визуально все ок, я пока оставила, посмотри

2021-12-06 15:37 UTC, Oliko136 approved these changes

2021-12-06 15:37 UTC, merged